name: auto update manifests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs at 00:00 UTC everyday

permissions:
  contents: write

env:
  has_updated: false

jobs:
  checkforupdate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install legendary-gl requests
      - name: execute py script
        run: |
          python autodownloader.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.filename }}
        if: env.has_updated == 'True'
